Function CreateAzureVMFromPackerTemplate {
    <#
        .SYNOPSIS
            A helper function to deploy a VM from a generated image.

        .DESCRIPTION
             Creates an Azure VM from a template. Also generates network resources in Azure to make the VM accessible.

        .PARAMETER SubscriptionId
            The Azure subscription Id where resources will be created.

        .PARAMETER ResourceGroupName
            The Azure resource group name where the Azure virtual machine will be created.

        .PARAMETER TemplatFilePath
            The path for the json template generated by packer during image generation locally.

        .PARAMETER VirtualMachineName
            The name of the virtual machine to be generated.

        .PARAMETER AdminUserName
            The administrator username for the virtual machine to be created.

        .PARAMETER AdminPassword
            The administrator password for the virtual machine to be created.

        .PARAMETER AzureLocation
            The location where the Azure virtual machine will be provisioned. Example: "eastus"

        .EXAMPLE
            CreateAzureVMFromPackerTemplate -SubscriptionId {YourSubscriptionId}  -ResourceGroupName {ResourceGroupName} -TemplateFile "C:\BuildVmImages\temporaryTemplate.json" -VirtualMachineName "testvm1" -AdminUsername "shady1" -AdminPassword "SomeSecurePassword1" -AzureLocation "eastus"
    #>
    param (
        [Parameter(Mandatory = $True)]
        [string] $SubscriptionId,
        [Parameter(Mandatory = $True)]
        [string] $ResourceGroupName,
        [Parameter(Mandatory = $True)]
        [string] $TemplateFilePath,
        [Parameter(Mandatory = $True)]
        [string] $VirtualMachineName,
        [Parameter(Mandatory = $True)]
        [string] $AdminUsername,
        [Parameter(Mandatory = $True)]
        [String] $AdminPassword,
        [Parameter(Mandatory = $True)]
        [string] $AzureLocation,
        [Parameter(Mandatory = $True)]
        [string] $vmSize,
        [Parameter(Mandatory = $True)]
        [string] $vnetName,
        [Parameter(Mandatory = $True)]
        [string] $subnetName,
        [Parameter(Mandatory = $True)]
        [string] $vnetresourcegroupname
        

    )

    $guid = [System.GUID]::NewGuid().ToString().ToUpper()
    $nicName = $VirtualMachineName
    
    $VNET = Get-AzVirtualNetwork -Name $vnetName -ResourceGroupName $vnetresourcegroupname
    $subnetid = $vnet.subnets[6].id

    $nic = New-Aznetworkinterface -name $VirtualMachineName -ResourceGroupName $ResourceGroupName -Location $azurelocation -subnetid $subnetid |ConvertFrom-Json
    ($nic = az network nic create -g $ResourceGroupName -l $AzureLocation -n $nicName --subnet $subnetId -o json)
    $networkId = ($nic | ConvertFrom-Json).NewNIC.id


    New-Azresourcegroupdeployment -ResourceGroupName $ResourceGroupName -name "ADO-Deploy-Packer" -TemplateFilename 
    Write-Host "`nCreating the VM"
    az group deployment create -g $ResourceGroupName -n $VirtualMachineName --template-file $templateFilePath --parameters vmSize=$vmSize vmName=$VirtualMachineName adminUserName=$AdminUsername adminPassword=$AdminPassword networkInterfaceId=$networkId
    
    Write-Host "`nCreated in ${ResourceGroupName}:`n  vnet ${vnetName}`n  subnet ${subnetName}`n  nic ${nicName}`n  publicip ${publicIpName}`n  vm ${VirtualMachineName}"
}
